### ISSUE TITLE
inner column overflow during resize

### ISSUE THREAD

**Issue by CLYeo** [kbrsh/wing#58]
hi,

I was testing responsiveness and encountered this.
what I was trying to achieve is items inside div 'col' content should not touch the edge

before 
![image](https://user-images.githubusercontent.com/29327709/27091965-5633842e-5094-11e7-8967-b810b78f4b7d.png)

after
![image](https://user-images.githubusercontent.com/29327709/27092021-8f7c3cc6-5094-11e7-9ae2-431d1ba0b5fd.png)

link to the testing code if required
http://www.cssdesk.com/BC8ku

cheers

**Comment by KingPixil** [comment]
You should be using a `.container` around the main grid. For now, nested columns/rows aren't supported, but I'll add this in v1.0.0.

**Comment by CLYeo** [comment]
ok got it, thanks
