### ISSUE TITLE
Grid's column width values may be incorrect

### ISSUE THREAD

**Issue by lentemarton** [kbrsh/wing#66]
Hello,

I've spotted some inconsistencies with the grid's percent-based column class' width values like `.col-1`, `.col-2`, `.col-3` etc., as they just doesn't add up well. When I combine two, or more 'equal-width' columns with simple `.col` class assigned to each, margin is four percent, which is all right. However when I combine two 'not-equal-width', or more columns e.g. `.col-2` with `.col-10`, or `.col-3` with `.col-4` and `.col-5`, just more margin remains. It's because width values may be incorrect – there is always four percent 'extra' margin remained – distributed equally because of `justify-content: space-between` styling applied. I guess, margin was meant to be consistent with all column-combinations, so I think they'd be worth checking.

If I'm right, here are the correct values, recalculated for a consistent four-percent-margin:
```
.col-1 {
  width: 4.666666666666667%;
}

.col-2 {
  width: 13.333333333333333%;
}

.col-3 {
  width: 22%;
}

.col-4 {
  width: 30.66666666666667%;
}

.col-5 {
  width: 39.33333333333333%;
}

.col-6 {
  width: 48%;
}

.col-7 {
  width: 56.666666666666667%;
}

.col-8 {
  width: 65.33333333333333%;
}

.col-9 {
  width: 74%;
}

.col-10 {
  width: 82.66666666666667%;
}

.col-11 {
  width: 91.33333333333333%;
}

.col-12 {
  width: 100%;
}
```

I've tested this, seems to be working as expected. Please let me know if the above is correct, or I just don't get something!

Maybe shall I've created a pull request instead?

Thank you in advance!

Kind regards,
Márton Lente

**Comment by kbrsh** [comment]
Hey! Sorry for the late response. I've been rewriting Wing lately, and it should be fixed.
