### ISSUE TITLE
Lack of proper browser support documentation

### ISSUE THREAD

**Issue by danivijay** [kbrsh/wing#74]
It seems like **Wing** is not designed to work everywhere. Some of our products requires more browser support and some requires less. 

Testing, defining and displaying the **browser support** is essential to choose whether it can be used for production.

Hopes @kbrsh will look into this.

**Comment by kbrsh** [comment]
Wing is supported in all modern browsers that support flexbox  (IE11+). The website itself includes some messy styles that I intend to fix.

Wing is currently not intended for production use (it is in 1.0.0-beta). 1.0 is almost here (the current development version is on this branch). I just need to write the documentation.

**Comment by danivijay** [comment]
That helps. It seems [caniuse.com/#search=flexbox](https://caniuse.com/#search=flexbox) can be used as a reference, excluding partial supports(current grid fails in IE11).

![capture](https://user-images.githubusercontent.com/3250760/33924906-08d35f3e-dffe-11e7-9bb1-23061c0f62f4.PNG)
