### ISSUE TITLE
Grid's column width values are still incorrect

### ISSUE THREAD

**Issue by lentemarton** [kbrsh/wing#77]
Hello,

There may be a problem with the grid system's logic. Column widths are only correct in evenly distributed columns with `.col` class, as padding right values are always subtracted from other columns' widths, except of course last childs. You can easily spot the issue on the test screenshot, where the two colums with `.col-6` class shall be equal in width, but theye aren't – as the last child is wider with the padding right value.

!["2018 02 12 21 33 52](https://preview.ibb.co/hM37bS/2018_02_12_21_33_52.png)

This issue basically is present in all column-combinations, making the grid inaccurate. Let me know if I'm wrong!

Thank you in advance!

Kind regards,
Márton Lente

**Comment by lentemarton** [comment]
Hello,

Following `.col` class's logic, the following lines may solve the issue, applying on top of Wing CSS:

```
.row .col-1 {
  flex: 1 1 0px;
  width: auto;
}
.row .col-2 {
  flex: 2 1 0px;
  width: auto;
}
.row .col-3 {
  flex: 3 1 0px;
  width: auto;
}
.row .col-4 {
  flex: 4 1 0px;
  width: auto;
}
.row .col-5 {
  flex: 5 1 0px;
  width: auto;
}
.row .col-6 {
  flex: 6 1 0px;
  width: auto;
}
.row .col-7 {
  flex: 7 1 0px;
  width: auto;
}
.row .col-8 {
  flex: 8 1 0px;
  width: auto;
}
.row .col-9 {
  flex: 9 1 0px;
  width: auto;
}
.row .col-10 {
  flex: 10 1 0px;
  width: auto;
}
.row .col-11 {
  flex: 11 1 0px;
  width: auto;
}
.row .col-12 {
  flex: 12 1 0px;
  width: auto;
}
```

As well `width: auto;` isn't needed, if it isn't defined earlier in the style sheet. Testing is needed.

The `.col` class isn't needed to be used in pair with `.col-1` - `.col-12` classes.

Kind regards,
Márton Lente

**Comment by kbrsh** [comment]
Thanks again for the detailed issue :)

I think I've found a fix—columns had padding that I hadn't removed from previous versions, and it created an inconsistency between `.col` and `.col-x` columns.

Check out the latest `dist/wing.min.css` once this issue is closed and let me know if it works.

**Comment by lentemarton** [comment]
Hello,

Thank you for the clean and nice fix, it absolutely works!

In my opinion applying padding on both sides make more sense as well.

Kind regards,
Márton Lente
