### ISSUE TITLE
Website not loading?

### ISSUE THREAD

**Issue by yeltsinseal** [kbrsh/wing#81]
Hey,

Wing is one of the best framework in the market... But the website isn't working for me anymore. Do you know why?

**Comment by martonlente** [comment]
Hello,

I agree, and experience the same here – website doesn't load. It'd be nice to keep it alive!

**Comment by kbrsh** [comment]
Hey!

The domain (along with domains for lots of my other projects) got taken over by advertisers since the name was free. The new website should be available at [kbrsh.github.io/wing](https://kbrsh.github.io/wing).

**Comment by kbrsh** [comment]
No problem! Sorry for the inconvenience.
